### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by roelofsaj** [USRSE/monthly-community-calls#30]
- [ ] Put 'Add to calendar' button on recurring events on website
- [ ] Check with Sophia on whether she can coordinate with presenters for each community call on making recording public and then actually doing so
- [ ] Incorporate Dan's comments from slack in the breakout discussion docs:
  > In the "template" for community calls and specifically break outs, we might want to say what breakout groups should do, particularly for new groups:
  please take notes in ...
  assign someone to take notes
  figure out who will report back on the group
  figure out who will facilitate the group/discussion
  consider starting with brief introductions
  the breakout will be X minutes long
